version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: